"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ProgressProvider } from "./ProgressContext";
import ProgressBar from "./progress/ProgressBar";
import { usePathname } from "next/navigation";
import { useState } from "react";

const inter = Inter({
  weight: ['400', '700'],
  subsets: ['latin']
})

// export const metadata = {
//   title: "Главная страница",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const [ darkMode,  setdarkMode ] = useState(true)

  function handleTheme() {
    if(darkMode) {
      setdarkMode(false)
    } else {
      setdarkMode(true)
    }
  }
  
  return (
    <html lang="en">
      <body 
        className={inter.className}
        style={{
          background: darkMode ? "#333" : "white",
          color: darkMode ? "white" : "#333"
        }}
      >
          
        <ProgressProvider >

          
          <Header />
          <button onClick={handleTheme}>Поменять тему</button>
          <div className="container" >
            <div className="buttom">
              {children}
            </div>
            
            {pathname === "/about" && <ProgressBar />}
          </div>
          
        </ProgressProvider>
        
      </body>
    </html>
  );
}
