import Link from "next/link";
import { fetchData } from "../page";
import { lazy } from "react";

const PostLazy = lazy(() => import("@/components/Post"))

export const metadata = {
  title: "Страница постов",
  description: "Generated by create next app",
};

export default async function Home() {
  const res = await fetchData()
  return (
   <div className="">
    <h1>Посты</h1>
    {res.map((item) => (
      <div key={item.id} className="post">
        <PostLazy post={item} />
        <Link href={`/posts/${item.id}`}>Детальнее</Link>
      </div>
    ))}
   </div>
  );
}